repos:
  - repo: local
    hooks:
      - id: ruff
        name: Run Ruff (local)
        entry: ruff check --no-fix          
        language: system
        files: ^(app/|tests/) 
        types: [python]

  - repo: local
    hooks:
      - id: pytest
        name: Run Pytest
        entry: pytest tests/
        language: system
        pass_filenames: false  
