services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build:
      context: ..
      dockerfile: app/Dockerfile 
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ..:/app
    ports:
      - "8000:80"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
