version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: postgres  
      POSTGRES_DB: time_tracking  
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  
      interval: 10s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6388:6379"    
    environment:
      REDIS_HOST: redis  
      REDIS_PORT: 6379  
    volumes:
      - redis_data:/data

  app:
    build:
      context: ..
      dockerfile: app/Dockerfile
    command: sh -c "poetry install --with dev && poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - ../app:/app/app
      - ../alembic.ini:/app/alembic.ini
      - ../alembic:/app/alembic
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: time_tracking  
      POSTGRES_HOST: db  
      REDIS_HOST: redis  
      REDIS_PORT: 6379  

volumes:
  postgres_data:
  redis_data: